### ISSUE TITLE
数据表没有id字段，报错。

### ISSUE THREAD

**Issue by mygoda** [beastbikes/django-adminlte#14]
当我的数据表中没有id这个字段的时候，会报错，报错如下：     
`Cannot resolve keyword 'id' into field. Choices are`

**Comment by mygoda** [comment]
出错代码如下：
`@classmethod
    def from_request(cls, query, request):
        page = int(request.GET.get('page', 1))
        size = int(request.GET.get('size', 20))
        order_by = request.GET.get('order_by', '-id')`    
建议修改为：       
`@classmethod
    def from_request(cls, query, request):
        page = int(request.GET.get('page', 1))
        size = int(request.GET.get('size', 20))
        order_by = request.GET.get('order_by', '-pk')`

**Comment by ZhangBohan** [comment]
fixed，已升级SDK到0.5版本
