### ISSUE TITLE
导航菜单刷新的问题

### ISSUE THREAD

**Issue by nnfish** [beastbikes/django-adminlte#15]
非常感谢您的工作，集成到项目中非常方便。

有一个小问题想问一下是否可以改进，就是左侧的导航菜单，点击菜单项时页面重新加载
会让导航菜单也再次加载刷新，页面有闪烁

请问是否可以优化改进一下？

**Comment by ZhangBohan** [comment]
抱歉，该项目目前采用服务端渲染方案，点击菜单项时会重新请求页面，这个没办法避免，要修改这个需要做比较大的改动。
不过只要网速可以的话这个闪烁基本看不到
