### ISSUE TITLE
catch 'WSGIRequest' object has no attribute 'user' exception

### ISSUE THREAD

**Issue by mygoda** [beastbikes/django-adminlte#4]
now, when i want to use demo project, i catch `catch 'WSGIRequest' object has no attribute 'user' exception` . my django version is 1.8, so i think you should change  `MIDDLEWARE` settings to `MIDDLEWARE_CLASSES` that is work for django 1.8 or 1.10. i will push my code to branch

**Comment by mygoda** [comment]
oh no, i do not have permission.`fatal: unable to access 'https://github.com/beastbikes/django-adminlte.git/': The requested URL returned error: 403`

**Comment by ZhangBohan** [comment]
@mygoda you should open a pull request
